version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    network_mode: host
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/app
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev